name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "tecio/**/*.py"
    tags:
      - "update-docs*"
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: |
      !contains(github.event.head_commit.message, '[skip docs]') ||
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set TECIO_LIB
        run: |
          echo "TECIO_LIB=${{ github.workspace }}/lib/linux_x86_64/libtecio.so" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Build docs
        run: cd docs && make html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
